### ISSUE TITLE
运行一直提示如下

### ISSUE THREAD

**Issue by caprice** [wenmin-wu/QuestionGameAssist#1]

**Comment by wenmin-wu** [comment]
你是在windows在跑的吗？看起来像是截图解析问题，导致opencv decode失败，今天上午做了windows系统兼容，你可以更新下代码试试。
系统兼容changes见 https://github.com/wenmin-wu/QuestionGameAssist/commit/c06c0c9a6064f229d79ab21a30daa238329c65cb

**Comment by wenmin-wu** [comment]
https://github.com/wenmin-wu/QuestionGameAssist/commit/1bf2caa127323ae3b5c135f962f5161f103c3f2c

不好意思，刚才看了下，系统检测未使用 gobal 变量，刚修复了下
